services:
  backend:
    build: .
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL=http://backend:8000/model/predict_stream
    ports:
      - "8501:8501"
    depends_on:
      - backend 